import { ClientProvider } from "@/config/client-provider";
import { Flex, Layout, Header, Content } from "@/components/ui";
import { DEFUALT_THEME_COLOR } from "@/constants/globals";
import { fontPoppins } from "@/utils/fonts";
import NextImage from "@/components/next-image";
import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen font-sans antialiased ${fontPoppins.variable}`}
      >
        <ClientProvider>
          <Layout>
            <Content>
              <Header style={{ background: DEFUALT_THEME_COLOR }}>
                <Flex align="center" style={{ height: "100%" }}>
                  <NextImage
                    src="/next.svg"
                    alt="Next.js Logo"
                    style={{ width: 100 }}
                  />
                </Flex>
              </Header>
              {children}
            </Content>
          </Layout>
        </ClientProvider>
      </body>
    </html>
  );
}
