import { ClientProvider } from "@/config/client-provider";
import { fontPoppins } from "@/utils/fonts";
import { cn } from "@/utils/tailwind";
import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          fontPoppins.variable,
        )}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
